#include "nwiiu/analyzer/game_config.h"

#include "test_support.h"

#include <fstream>
#include <string>
#include <string_view>

namespace {
using nwiiu::analyzer::GameConfig;
using nwiiu::analyzer::parse_game_config;

// Custom delimiter: the title name below ends in `)"`, which would close a
// plain raw string mid-profile.
constexpr std::string_view kWwhdProfile = R"toml(
# The profile the tree used to hardcode.
project_name = "Wind Waker HD"
output_dir   = "export/wwhd"

[system]
platform = "WiiU"

[target]
product_code  = "WUP-P-BCZP"
title_id      = "0005000010143600"
title_version = 0
sha256        = "f9f461738949a09481dc1a31c01ad27db813c4c6058fdd7d015624a4146bbf0b"
entry_point   = 0x028EA9E0
name          = "The Legend of Zelda: The Wind Waker HD (EU v0)"

[hle_hooks]
"0275F480" = "Yaz0Decode"   # SZS decompressor
)toml";

void test_profile_round_trips_every_field() {
    const GameConfig config = parse_game_config(kWwhdProfile);
    test::require(config.project_name == "Wind Waker HD", "project name");
    test::require(config.output_dir == "export/wwhd", "output dir");
    test::require(config.platform == "WiiU", "platform");
    test::require(config.target.product_code == "WUP-P-BCZP", "product code");
    test::require(config.target.title_id == "0005000010143600", "title id");
    test::require(config.target.entry_point == 0x028EA9E0, "entry point");
    test::require(config.target.sha256.size() == 64, "digest length");
    test::require(config.target.verifies_hash(), "digest gates the load");
    test::require(config.target.pins_entry_point(), "entry point is pinned");
    test::require(config.hle_hooks.size() == 1, "hook count");
    test::require(config.hle_hooks.at(0x0275F480) == "Yaz0Decode",
                  "hook address decodes as bare hex");
}

void test_absent_gates_leave_the_profile_permissive() {
    const GameConfig config = parse_game_config("project_name = \"any\"\n");
    test::require(!config.target.verifies_hash(),
                  "a profile without a digest authenticates nothing");
    test::require(!config.target.pins_entry_point(),
                  "a profile without an entry point adopts the image's");
    test::require(config.target.name == "any",
                  "the project name stands in for a missing title name");
    test::require(config.hle_hooks.empty(), "no hooks by default");
}

void test_verify_hash_false_drops_the_digest_without_deleting_it() {
    const GameConfig config = parse_game_config(
        "project_name = \"x\"\n[target]\nsha256 = \"abcd\"\n"
        "verify_hash = false\n");
    test::require(!config.target.verifies_hash(),
                  "verify_hash = false clears the gate");
}

void test_comments_and_blank_lines_are_ignored() {
    const GameConfig config = parse_game_config(
        "# leading comment\n\n  project_name = \"x\"  # trailing\n\n"
        "[hle_hooks]\n\"1000\" = \"A\" # named\n");
    test::require(config.project_name == "x", "comment stripping");
    test::require(config.hle_hooks.at(0x1000) == "A", "hook past a comment");
}

void test_a_hash_inside_a_string_is_not_a_comment() {
    const GameConfig config =
        parse_game_config("project_name = \"a#b\"\n");
    test::require(config.project_name == "a#b", "quoted hash survives");
}

void test_target_prefix_is_a_usable_cmake_identifier() {
    GameConfig config;
    config.project_name = "The Legend of Zelda: Wind Waker HD";
    test::require(config.target_prefix() == "the-legend-of-zelda-wind-waker-hd",
                  "punctuation and spaces collapse to single dashes");
    config.project_name = "2 Fast";
    test::require(config.target_prefix() == "g2-fast",
                  "a leading digit is prefixed, not dropped");
    config.project_name = "!!!";
    test::require(config.target_prefix() == "g",
                  "an all-punctuation name still yields an identifier");
}

// The exact shape ExportWiiUProfile.java emits, including its commented-out
// optional gates and candidate hooks. If the script and the parser drift, a
// freshly exported profile stops loading — this is the contract between them.
void test_a_ghidra_exported_profile_loads() {
    constexpr std::string_view kExported = R"toml(
# Generated by ExportWiiUProfile.java from NFSMWU.rpx.
# Functions seen by Ghidra: 24187.
# Review every [hle_hooks] line before enabling it.

project_name  = "NFS Most Wanted U"
output_dir    = "export/nfs-most-wanted-u"
target_prefix = "nfs-most-wanted-u"
symbols_csv   = "nfs-most-wanted-u-symbols.csv"

[system]
platform = "WiiU"

[target]
# product_code = ""
# title_id = ""
title_version = 0
sha256        = "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee"
entry_point   = 0x02010000
name          = "NFS Most Wanted U"

[hle_hooks]
"02345678" = "Yaz0Decode"  # decompressSZS
# "02345700" = "MemCopy"  # memcpy_fast - no native implementation yet
)toml";

    const GameConfig config = parse_game_config(kExported);
    test::require(config.target_prefix() == "nfs-most-wanted-u",
                  "the script's prefix survives verbatim");
    test::require(config.symbols_csv == "nfs-most-wanted-u-symbols.csv",
                  "the symbol export path round-trips");
    test::require(config.target.product_code.empty(),
                  "a commented-out gate stays unset");
    test::require(config.target.entry_point == 0x02010000, "entry point");
    test::require(config.hle_hooks.size() == 1,
                  "only the uncommented hook is live");
    test::require(config.hle_hooks.at(0x02345678) == "Yaz0Decode", "hook name");
}

void test_malformed_input_names_the_line() {
    test::require_throws([] { parse_game_config("project_name\n"); },
                         "line 1", "missing '=' reports its line");
    test::require_throws(
        [] { parse_game_config("project_name = \"x\"\nbogus = 1\n"); },
        "unknown key", "unknown root keys are rejected");
    test::require_throws(
        [] { parse_game_config("[nope]\n"); }, "unknown table",
        "unknown tables are rejected");
    test::require_throws(
        [] { parse_game_config("project_name = \"x\"\n[target]\nname = 5\n"); },
        "expected a quoted string", "type mismatch is rejected");
    test::require_throws(
        [] {
            parse_game_config(
                "project_name = \"x\"\n[hle_hooks]\n\"zz\" = \"A\"\n");
        },
        "expected a guest address", "a non-hex hook key is rejected");
    test::require_throws(
        [] {
            parse_game_config("project_name = \"x\"\n[hle_hooks]\n"
                               "\"10\" = \"A\"\n\"10\" = \"B\"\n");
        },
        "duplicate hook address", "a repeated hook address is rejected");
    test::require_throws([] { parse_game_config("a = \"b\n"); },
                         "unterminated string", "an unclosed quote is caught");
}

void test_load_reads_a_file_and_records_its_path() {
    test::TempDir temp;
    const auto path = temp.path() / "profile.toml";
    std::ofstream(path) << kWwhdProfile;
    const GameConfig config = nwiiu::analyzer::load_game_config(path);
    test::require(config.source_path == path, "source path is recorded");
    test::require(config.target.entry_point == 0x028EA9E0, "file parses");
    test::require_throws(
        [&] { nwiiu::analyzer::load_game_config(temp.path() / "missing"); },
        "cannot open config", "a missing profile is reported");
}
} // namespace

int main() {
    test_profile_round_trips_every_field();
    test_absent_gates_leave_the_profile_permissive();
    test_verify_hash_false_drops_the_digest_without_deleting_it();
    test_comments_and_blank_lines_are_ignored();
    test_a_hash_inside_a_string_is_not_a_comment();
    test_target_prefix_is_a_usable_cmake_identifier();
    test_a_ghidra_exported_profile_loads();
    test_malformed_input_names_the_line();
    test_load_reads_a_file_and_records_its_path();
}
